[uwsgi]
main_plugin = python,gevent
inherit = base
; We're disabling XML support on build to fix version mismatch issues with python packages
; https://github.com/xmlsec/python-xmlsec/issues/320#issuecomment-3105889574
xml = no
